services:
  # base url: http://mealie:9000
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    ports:
      - "9925:9000" #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: America/Anchorage
    networks:
      skylite-ux_devcontainer_default:

volumes:
  mealie-data:

networks:
  skylite-ux_devcontainer_default:
    external: true
