name: Lint

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prepare Nuxt
        run: npm run build

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint