export type ChoreTemplate = {
  id: string;
  title: string;
  description: string;
  icon: string;
  category: string;
  points: number;
  color: string;
};

export const choreTemplates: ChoreTemplate[] = [
  {
    id: "listening",
    title: "Good Listening",
    description: "Listen when grown-ups are talking",
    icon: "i-lucide-ear",
    category: "behavior",
    points: 1,
    color: "blue",
  },
  {
    id: "make-bed",
    title: "Make Your Bed",
    description: "Make your bed neat and tidy",
    icon: "i-lucide-bed-double",
    category: "cleaning",
    points: 1,
    color: "purple",
  },
  {
    id: "brush-teeth",
    title: "Brush Teeth",
    description: "Brush your teeth morning and night",
    icon: "i-lucide-sparkles",
    category: "hygiene",
    points: 1,
    color: "cyan",
  },
  {
    id: "take-bath",
    title: "Take a Bath",
    description: "Take a nice bath or shower",
    icon: "i-lucide-shower-head",
    category: "hygiene",
    points: 1,
    color: "blue",
  },
  {
    id: "clean-room",
    title: "Clean Your Room",
    description: "Pick up toys and keep room tidy",
    icon: "i-lucide-home",
    category: "cleaning",
    points: 2,
    color: "green",
  },
  {
    id: "clean-toys",
    title: "Put Toys Away",
    description: "Put all toys back in their place",
    icon: "i-lucide-blocks",
    category: "cleaning",
    points: 1,
    color: "orange",
  },
  {
    id: "help-dishes",
    title: "Help with Dishes",
    description: "Help clear the table or wash dishes",
    icon: "i-lucide-utensils",
    category: "meal",
    points: 2,
    color: "yellow",
  },
  {
    id: "set-table",
    title: "Set the Table",
    description: "Help set the table for meals",
    icon: "i-lucide-utensils-crossed",
    category: "meal",
    points: 1,
    color: "red",
  },
  {
    id: "eat-vegetables",
    title: "Eat Your Vegetables",
    description: "Finish your healthy vegetables",
    icon: "i-lucide-carrot",
    category: "meal",
    points: 1,
    color: "green",
  },
  {
    id: "homework",
    title: "Do Homework",
    description: "Complete school homework",
    icon: "i-lucide-book-open",
    category: "learning",
    points: 2,
    color: "indigo",
  },
  {
    id: "reading",
    title: "Reading Time",
    description: "Read a book for 15 minutes",
    icon: "i-lucide-book",
    category: "learning",
    points: 2,
    color: "purple",
  },
  {
    id: "feed-pet",
    title: "Feed the Pet",
    description: "Feed and give water to pets",
    icon: "i-lucide-dog",
    category: "pet-care",
    points: 1,
    color: "amber",
  },
  {
    id: "water-plants",
    title: "Water Plants",
    description: "Water the plants or garden",
    icon: "i-lucide-sprout",
    category: "chores",
    points: 1,
    color: "green",
  },
  {
    id: "take-out-trash",
    title: "Take Out Trash",
    description: "Help take out the garbage",
    icon: "i-lucide-trash-2",
    category: "chores",
    points: 2,
    color: "gray",
  },
  {
    id: "help-laundry",
    title: "Help with Laundry",
    description: "Help sort or fold laundry",
    icon: "i-lucide-shirt",
    category: "chores",
    points: 2,
    color: "blue",
  },
  {
    id: "kind-sibling",
    title: "Be Kind to Siblings",
    description: "Play nicely with brothers/sisters",
    icon: "i-lucide-heart",
    category: "behavior",
    points: 1,
    color: "pink",
  },
  {
    id: "say-please-thanks",
    title: "Say Please & Thank You",
    description: "Use good manners all day",
    icon: "i-lucide-smile",
    category: "behavior",
    points: 1,
    color: "yellow",
  },
  {
    id: "practice-instrument",
    title: "Practice Instrument",
    description: "Practice music for 15 minutes",
    icon: "i-lucide-music",
    category: "learning",
    points: 2,
    color: "purple",
  },
  // New chores for ages 4-6
  {
    id: "get-dressed",
    title: "Get Dressed",
    description: "Put on clothes by yourself with buttons or zippers",
    icon: "i-lucide-shirt",
    category: "hygiene",
    points: 2,
    color: "teal",
  },
  {
    id: "brush-hair",
    title: "Brush Your Hair",
    description: "Brush or comb your hair nicely",
    icon: "i-lucide-sparkles",
    category: "hygiene",
    points: 1,
    color: "pink",
  },
  {
    id: "put-away-shoes",
    title: "Put Away Shoes & Coat",
    description: "Put shoes and coat in their special spot",
    icon: "i-lucide-home",
    category: "cleaning",
    points: 1,
    color: "brown",
  },
  {
    id: "empty-trash",
    title: "Empty Small Trash",
    description: "Empty small trash cans into the big bin",
    icon: "i-lucide-trash-2",
    category: "chores",
    points: 1,
    color: "slate",
  },
  {
    id: "dust-furniture",
    title: "Dust Furniture",
    description: "Wipe dust off furniture with a cloth",
    icon: "i-lucide-sparkles",
    category: "cleaning",
    points: 1,
    color: "sky",
  },
  {
    id: "clear-dishes",
    title: "Clear Your Dishes",
    description: "Take your plate and cup to the sink",
    icon: "i-lucide-utensils",
    category: "meal",
    points: 1,
    color: "orange",
  },
  {
    id: "help-cook",
    title: "Help Cook Simple Meals",
    description: "Help make a sandwich or stir batter",
    icon: "i-lucide-chef-hat",
    category: "meal",
    points: 2,
    color: "red",
  },
  {
    id: "pull-weeds",
    title: "Help in the Garden",
    description: "Pull weeds or collect leaves into a pile",
    icon: "i-lucide-leaf",
    category: "chores",
    points: 2,
    color: "green",
  },
];

export const choreCategories = [
  { id: "all", name: "All Chores", icon: "i-lucide-list" },
  { id: "behavior", name: "Good Behavior", icon: "i-lucide-smile" },
  { id: "hygiene", name: "Hygiene", icon: "i-lucide-sparkles" },
  { id: "cleaning", name: "Cleaning", icon: "i-lucide-broom" },
  { id: "meal", name: "Meal Time", icon: "i-lucide-utensils" },
  { id: "learning", name: "Learning", icon: "i-lucide-book" },
  { id: "pet-care", name: "Pet Care", icon: "i-lucide-dog" },
  { id: "chores", name: "Other Chores", icon: "i-lucide-check-circle" },
];


