export interface RewardTemplate {
  id: string;
  title: string;
  description: string;
  icon: string;
  category: "screen-time" | "treats" | "activities" | "privileges" | "toys" | "special";
  pointCost: number;
  color: string;
}

export const rewardTemplates: RewardTemplate[] = [
  // Screen Time Rewards
  {
    id: "extra-tablet-15",
    title: "15 Min Extra Tablet Time",
    description: "Enjoy an extra 15 minutes on the tablet",
    icon: "i-lucide-tablet",
    category: "screen-time",
    pointCost: 15,
    color: "blue",
  },
  {
    id: "extra-tv-15",
    title: "15 Min Extra TV Time",
    description: "Watch an extra 15 minutes of your favorite show",
    icon: "i-lucide-tv",
    category: "screen-time",
    pointCost: 15,
    color: "blue",
  },
  {
    id: "movie-night",
    title: "Pick Family Movie",
    description: "Choose the movie for family movie night",
    icon: "i-lucide-film",
    category: "screen-time",
    pointCost: 25,
    color: "blue",
  },
  {
    id: "game-time-15",
    title: "15 Min Game Time",
    description: "Fifteen minutes of video game time",
    icon: "i-lucide-gamepad-2",
    category: "screen-time",
    pointCost: 15,
    color: "blue",
  },
  {
    id: "youtube-video",
    title: "Pick a YouTube Video",
    description: "Choose one fun video to watch together",
    icon: "i-lucide-play-circle",
    category: "screen-time",
    pointCost: 15,
    color: "blue",
  },

  // Treats & Snacks
  {
    id: "ice-cream",
    title: "Ice Cream Treat",
    description: "Pick your favorite ice cream flavor",
    icon: "i-lucide-ice-cream-cone",
    category: "treats",
    pointCost: 20,
    color: "pink",
  },
  {
    id: "candy-small",
    title: "Small Sweet Treat",
    description: "Choose a small candy or sweet",
    icon: "i-lucide-candy",
    category: "treats",
    pointCost: 15,
    color: "pink",
  },
  {
    id: "special-dessert",
    title: "Favorite Dessert",
    description: "Your favorite dessert after dinner",
    icon: "i-lucide-cake",
    category: "treats",
    pointCost: 20,
    color: "pink",
  },
  {
    id: "snack-choice",
    title: "Pick Your Snack",
    description: "Choose any snack from the pantry",
    icon: "i-lucide-cookie",
    category: "treats",
    pointCost: 15,
    color: "pink",
  },
  {
    id: "juice-box",
    title: "Special Juice Box",
    description: "Pick a special juice or drink",
    icon: "i-lucide-cup-soda",
    category: "treats",
    pointCost: 15,
    color: "pink",
  },
  {
    id: "bake-cookies",
    title: "Bake Cookies Together",
    description: "Make and decorate cookies with parent",
    icon: "i-lucide-cookie",
    category: "treats",
    pointCost: 30,
    color: "pink",
  },

  // Activities
  {
    id: "park-visit",
    title: "Trip to the Park",
    description: "Special visit to your favorite park",
    icon: "i-lucide-trees",
    category: "activities",
    pointCost: 40,
    color: "green",
  },
  {
    id: "craft-time",
    title: "Craft Project Time",
    description: "Do a special craft project with parent",
    icon: "i-lucide-palette",
    category: "activities",
    pointCost: 25,
    color: "green",
  },
  {
    id: "playground-date",
    title: "Friend Playdate",
    description: "Invite a friend over to play",
    icon: "i-lucide-users",
    category: "activities",
    pointCost: 50,
    color: "green",
  },
  {
    id: "library-trip",
    title: "Library Visit",
    description: "Trip to library to pick new books",
    icon: "i-lucide-book",
    category: "activities",
    pointCost: 30,
    color: "green",
  },
  {
    id: "board-game",
    title: "Family Board Game",
    description: "Choose a board game to play together",
    icon: "i-lucide-dice-6",
    category: "activities",
    pointCost: 20,
    color: "green",
  },
  {
    id: "one-on-one-time",
    title: "Special Parent Time",
    description: "15 minutes of one-on-one time with parent",
    icon: "i-lucide-heart",
    category: "activities",
    pointCost: 25,
    color: "green",
  },
  {
    id: "outdoor-play",
    title: "Outdoor Adventure",
    description: "Special outdoor play session",
    icon: "i-lucide-bike",
    category: "activities",
    pointCost: 30,
    color: "green",
  },
  {
    id: "story-time",
    title: "Extra Story Time",
    description: "Parent reads 2 extra stories at bedtime",
    icon: "i-lucide-book-open",
    category: "activities",
    pointCost: 15,
    color: "green",
  },
  {
    id: "dance-party",
    title: "Dance Party",
    description: "Have a fun dance party with music",
    icon: "i-lucide-music",
    category: "activities",
    pointCost: 15,
    color: "green",
  },
  {
    id: "puzzle-time",
    title: "Puzzle Together",
    description: "Work on a puzzle with parent",
    icon: "i-lucide-puzzle",
    category: "activities",
    pointCost: 20,
    color: "green",
  },

  // Privileges
  {
    id: "stay-up-15",
    title: "Stay Up 15 Min Later",
    description: "Extend bedtime by 15 minutes",
    icon: "i-lucide-moon",
    category: "privileges",
    pointCost: 25,
    color: "purple",
  },
  {
    id: "breakfast-choice",
    title: "Choose Breakfast",
    description: "Pick what's for breakfast tomorrow",
    icon: "i-lucide-sunrise",
    category: "privileges",
    pointCost: 15,
    color: "purple",
  },
  {
    id: "dinner-choice",
    title: "Choose Dinner",
    description: "Pick what's for dinner tonight",
    icon: "i-lucide-utensils",
    category: "privileges",
    pointCost: 30,
    color: "purple",
  },
  {
    id: "skip-one-chore",
    title: "Skip One Chore",
    description: "Skip one chore for the day",
    icon: "i-lucide-skip-forward",
    category: "privileges",
    pointCost: 20,
    color: "purple",
  },
  {
    id: "chore-free-day",
    title: "Chore-Free Day",
    description: "No chores for the whole day!",
    icon: "i-lucide-sun",
    category: "privileges",
    pointCost: 100,
    color: "purple",
  },
  {
    id: "music-choice",
    title: "Music in Car",
    description: "Pick music for the car ride",
    icon: "i-lucide-music",
    category: "privileges",
    pointCost: 15,
    color: "purple",
  },
  {
    id: "wear-pajamas",
    title: "Pajama Day",
    description: "Stay in pajamas all day at home",
    icon: "i-lucide-shirt",
    category: "privileges",
    pointCost: 20,
    color: "purple",
  },
  {
    id: "choose-activity",
    title: "Pick Family Activity",
    description: "Choose what the family does today",
    icon: "i-lucide-smile",
    category: "privileges",
    pointCost: 35,
    color: "purple",
  },
  {
    id: "allowance-bonus",
    title: "Small Allowance Bonus",
    description: "Earn $1 extra allowance",
    icon: "i-lucide-coins",
    category: "privileges",
    pointCost: 50,
    color: "purple",
  },

  // Toys & Items
  {
    id: "small-toy",
    title: "Small Toy (Under $5)",
    description: "Choose a small toy from the store",
    icon: "i-lucide-toy-brick",
    category: "toys",
    pointCost: 75,
    color: "orange",
  },
  {
    id: "stickers-pack",
    title: "Sticker Pack",
    description: "Get a new pack of stickers",
    icon: "i-lucide-sticker",
    category: "toys",
    pointCost: 25,
    color: "orange",
  },
  {
    id: "coloring-book",
    title: "New Coloring Book",
    description: "Pick out a new coloring book",
    icon: "i-lucide-pen-tool",
    category: "toys",
    pointCost: 40,
    color: "orange",
  },
  {
    id: "new-book",
    title: "New Book",
    description: "Choose a new book to read",
    icon: "i-lucide-book-open",
    category: "toys",
    pointCost: 50,
    color: "orange",
  },
  {
    id: "art-supplies",
    title: "Art Supplies",
    description: "New markers, crayons, or art materials",
    icon: "i-lucide-paintbrush",
    category: "toys",
    pointCost: 45,
    color: "orange",
  },
  {
    id: "trading-cards",
    title: "Trading Card Pack",
    description: "Get a pack of collectible cards",
    icon: "i-lucide-badge",
    category: "toys",
    pointCost: 30,
    color: "orange",
  },

  // Special Big Rewards
  {
    id: "zoo-trip",
    title: "Zoo or Aquarium Visit",
    description: "Special family trip to zoo or aquarium",
    icon: "i-lucide-paw-print",
    category: "special",
    pointCost: 200,
    color: "red",
  },
  {
    id: "sleepover",
    title: "Friend Sleepover",
    description: "Have a friend over for a sleepover",
    icon: "i-lucide-home",
    category: "special",
    pointCost: 100,
    color: "red",
  },
  {
    id: "special-outing",
    title: "Special Day Out",
    description: "One-on-one special outing with parent",
    icon: "i-lucide-heart",
    category: "special",
    pointCost: 150,
    color: "red",
  },
  {
    id: "big-toy",
    title: "Big Toy (Under $20)",
    description: "Save up for a bigger toy",
    icon: "i-lucide-gift",
    category: "special",
    pointCost: 250,
    color: "red",
  },
  {
    id: "swimming-class",
    title: "Extra Swimming Class",
    description: "One additional swimming lesson",
    icon: "i-lucide-waves",
    category: "special",
    pointCost: 150,
    color: "red",
  },
  {
    id: "gymnastic-class",
    title: "Extra Gymnastics Class",
    description: "One additional gymnastics session",
    icon: "i-lucide-dumbbell",
    category: "special",
    pointCost: 150,
    color: "red",
  },
  {
    id: "restaurant-choice",
    title: "Pick the Restaurant",
    description: "Choose where family eats out",
    icon: "i-lucide-utensils-crossed",
    category: "special",
    pointCost: 80,
    color: "red",
  },
  {
    id: "mini-golf",
    title: "Mini Golf Outing",
    description: "Go play mini golf as a family",
    icon: "i-lucide-flag",
    category: "special",
    pointCost: 100,
    color: "red",
  },
  {
    id: "movie-theater",
    title: "Movie Theater Trip",
    description: "Go see a movie at the theater",
    icon: "i-lucide-popcorn",
    category: "special",
    pointCost: 120,
    color: "red",
  },
];

export const rewardCategories = [
  { id: "all", name: "All Rewards", icon: "i-lucide-gift" },
  { id: "screen-time", name: "Screen Time", icon: "i-lucide-tablet" },
  { id: "treats", name: "Treats & Snacks", icon: "i-lucide-candy" },
  { id: "activities", name: "Activities", icon: "i-lucide-palette" },
  { id: "privileges", name: "Privileges", icon: "i-lucide-star" },
  { id: "toys", name: "Toys & Items", icon: "i-lucide-toy-brick" },
  { id: "special", name: "Special Rewards", icon: "i-lucide-sparkles" },
];

